### ISSUE TITLE
Support more validators to work with a collection of primitive types

### ISSUE THREAD

**Issue by akkie** [biblius/validify#36]
Hi,

first I want to say thank you for this really good addition to the original validator crate. This is awesome. I really like the payload thing. That's a really good idea. Thank you!

To the issue itself. It seems that it's currently possible to define as example the `length` validator for a `Vec<String>` but not the `regex` validator. Even the `range` validators do not work on a `Vec<u16>`.

It would be great if all the primitive validators are working on a collection of primitive values.

**Comment by akkie** [comment]
OK, it seems that the validation itself for a collection with primitive types does not work at all.

If I define the following struct:

```rust
#[derive(Serialize, Deserialize, Validify, Payload)]
pub struct Params {
    #[validate(length(min = 1, max = 5, message = "Must between 1 and 5 chars long.", code = "5"))]
    pub option: Vec<String>,
}
```

and try to validate it, the length validator doesn't work.

**Comment by biblius** [comment]
Hello! 
Thanks for the kind words :)

The example you provided is working as intended because the function of the length validator is to validate the length of the vector itself, not its contents.

Nonetheless, you bring up a valid point. At one point I do plan on adding a `validate_iter` attribute to cover types that implement `Iterator`, making it possible to validate each element in a collection by reusing validators for single types.

Until then, the workaround for your case would be to define a custom validator and manually iterate through the vector and validate its elements.

Cheers!

**Comment by akkie** [comment]
Thanks, it works as expected! I'll close the issue.
